# Project Information
site_name: 'CS Notes'
site_description: 'A site for saving CS notes'
site_author: 'Harry Wu'
site_url: 'http://csnotes.dhwuho.xyz/'

# for test
dev_addr: 192.168.164.130:8000

# Repository
repo_name: 'dh-wuho/CS-Notes'
repo_url: 'https://github.com/dh-wuho/CS-Notes'

# Theme Configuration
theme:
    name: 'material'
    palette:
        primary: blue
        accent: indigo
    logo:
        icon: 'computer'

# Customization
extra:
    manifest: 'manifest.webmanifest'
    social:

# extra css and js for katex
extra_css:
    - 'css/katex.css'
    - 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.css'

extra_javascript:
    - 'js/katex.js'
    - 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.js'
    - 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/contrib/auto-render.min.js'

# Google Analytics
google_analytics:

# Mkdocs Extensions

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 dhwuho'

# Left Navigation
nav:
    - Home: index.md

    - CSC568 Enterprise Storage:
        - Preface: csc568/0-index.md
        - 10 - SAN: csc568/10-SAN.md
        - 11 - NAS: csc568/11-NAS.md
        - 12 - DFS: csc568/12-DFS.md
        - 13 - Ceph: csc568/13-Ceph.md
        - 14 - GFS: csc568/14-GFS.md
        - 15 - LFS: csc568/15-LFS.md
        - 16 - Redundancy: csc568/16-Redundancy.md
        - 17 - Deduplication: csc568/17-Deduplication.md
        - 18 - GNR: csc568/18-GNR.md
        - 19 - Erasure Encoding: csc568/19-Erasure-Encoding.md
        - 20 - Business Continuity: csc568/20-Business-Continuity.md
        - 21 - SCM: csc568/21-SCM.md
        - 23 - Haystack: csc568/23-Haystack.md
        - 24 - Disasters: csc568/24-Disasters.md
        - 25 - DevFS: csc568/25-DevFS.md
        - 26 - SSD Reliability: csc568/26-SSD-Reliability.md