# Project Information
site_name: 'CS Notes'
site_description: 'A site for saving CS notes'
site_author: 'Harry Wu'
site_url: 'http://csnotes.dhwuho.xyz/'

# Repository
repo_name: 'dh-wuho/CS-Notes'
repo_url: 'https://github.com/dh-wuho/CS-Notes'

# Theme Configuration
theme:
    name: 'material'
    palette:
        primary: blue
        accent: indigo
    logo:
        icon: 'computer'

# Customization
extra:
    manifest: 'manifest.webmanifest'
    social:

# extra css and js for katex
extra_css:
    - 'css/katex.css'
    - 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.css'

extra_javascript:
    - 'js/katex.js'
    - 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.js'
    - 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/contrib/auto-render.min.js'

# Google Analytics
google_analytics:

# Mkdocs Extensions

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 dhwuho'

# Left Navigation
nav:
    - Home: index.md
    - CSC568 Enterprise Storage:
        - Preface: csc568/0-index.md
        - 10 - SAN: csc568/10-SAN.md
        - 11 - NAS: csc568/11-NAS.md
        - 12 - DFS: csc568/12-DFS.md
        - 13 - Ceph: csc568/13-Ceph.md
        - 14 - GFS: csc568/14-GFS.md
    
    - CSC541 Advanced Data Structure:
        - Preface: csc541/index.md
        - Interval Tree: csc541/interval-tree.md